services:
  - type: web
    name: spinplus
    runtime: python
    plan: free
    region: oregon # or frankfurt/singapore
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "sh scripts/entrypoint.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: SITE_URL
        sync: false
      - key: ENABLE_HTTPS_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
