# Generated by Django 5.2.9 on 2026-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='losing_message',
            field=models.CharField(default='Better luck next time!', max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='spin_button_text',
            field=models.CharField(default='SPIN NOW', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='terms_conditions',
            field=models.TextField(blank=True, default='Valid for single spin per visit. Show coupon code to staff at checkout.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='welcome_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='welcome_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='campaign',
            name='winning_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='winning_title',
            field=models.CharField(default='CONGRATULATIONS!', max_length=150),
        ),
        migrations.AddField(
            model_name='coupon',
            name='verify_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=10),
        ),
        migrations.AddField(
            model_name='shopbranding',
            name='font_family',
            field=models.CharField(choices=[('inter', 'Inter (Modern)'), ('poppins', 'Poppins (Friendly)'), ('outfit', 'Outfit (Tech)'), ('playfair', 'Playfair Display (Luxury)'), ('space_grotesk', 'Space Grotesk (Futuristic)'), ('cinzel', 'Cinzel (Elegant)')], default='inter', max_length=30),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live / Active'), ('active', 'Active'), ('ended', 'Ended'), ('disabled', 'Disabled')], default='live', max_length=20),
        ),
    ]
