# Generated by Django 5.2.9 on 2026-08-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plan_shop_onboarding_completed_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_heroes/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
