# Generated by Django 5.2.9 on 2026-08-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_shopbranding_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbranding',
            name='theme',
            field=models.CharField(choices=[('royal', 'Royal Gold'), ('luxury_black', 'Luxury Black'), ('pearl', 'Pearl Beauty'), ('emerald', 'Emerald'), ('burgundy', 'Burgundy Fashion'), ('modern_blue', 'Modern Blue'), ('neon', 'Neon Cyber'), ('festival', 'Festival Celebration'), ('diwali', 'Diwali Lights'), ('navratri', 'Navratri Garba'), ('christmas', 'Christmas Holiday'), ('new_year', 'New Year Sparkle'), ('restaurant', 'Restaurant Dining'), ('coffee', 'Coffee Café'), ('playful', 'Playful Kids'), ('candy', 'Candy Sweet'), ('sports', 'Sports Energy'), ('minimal', 'Minimal Clean'), ('glass', 'Glassmorphism'), ('aurora', 'Aurora Glow'), ('sunset', 'Sunset Warmth'), ('ocean', 'Ocean Wave'), ('floral', 'Floral Blossom'), ('premium_white', 'Premium White'), ('custom', 'Custom Theme')], default='royal', max_length=50),
        ),
    ]
