# Generated by Django 5.2.9 on 2026-08-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_shopbranding_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbranding',
            name='theme',
            field=models.CharField(choices=[('royal', 'Royal Gold'), ('luxury_black', 'Luxury Black'), ('pearl', 'Pearl Luxury'), ('aurora', 'Aurora'), ('glass', 'Glassmorphism'), ('neon', 'Cyber Neon'), ('emerald', 'Emerald'), ('burgundy', 'Burgundy Fashion'), ('modern_blue', 'Modern Blue'), ('festival', 'Festival Celebration'), ('diwali', 'Diwali Lights'), ('navratri', 'Navratri Garba'), ('holi', 'Holi Color Splash'), ('christmas', 'Christmas Holiday'), ('new_year', 'New Year Sparkle'), ('eid', 'Eid Celebration'), ('valentines', 'Valentine Romance'), ('summer_sale', 'Summer Tropical Sale'), ('winter_sale', 'Winter Frost Sale'), ('monsoon_sale', 'Monsoon Splash Sale'), ('flash_sale', 'Flash Sale Lightning'), ('clearance', 'Clearance Sale'), ('restaurant', 'Restaurant Dining'), ('coffee', 'Coffee Café'), ('playful', 'Playful Kids'), ('candy', 'Candy Sweet'), ('sports', 'Sports Energy'), ('minimal', 'Minimal Clean'), ('sunset', 'Sunset Warmth'), ('ocean', 'Ocean Wave'), ('floral', 'Floral Blossom'), ('premium_white', 'Premium White'), ('custom', 'Custom Theme')], default='royal', max_length=50),
        ),
    ]
