# Generated by Django 5.2.9 on 2026-08-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_shopbranding_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
