# Generated by Django 5.2.9 on 2026-08-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_campaign_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbranding',
            name='accent_color',
            field=models.CharField(default='#ffd700', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='background_color',
            field=models.CharField(default='#0a060d', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='button_color',
            field=models.CharField(default='#d4af37', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='font_family',
            field=models.CharField(choices=[('inter', 'Inter (Modern Clean)'), ('poppins', 'Poppins (Friendly & Festive)'), ('outfit', 'Outfit (Modern Tech)'), ('playfair', 'Playfair Display (Luxury Serif)'), ('space_grotesk', 'Space Grotesk (Futuristic / Cyber)'), ('cinzel', 'Cinzel (Royal Heritage)')], default='cinzel', max_length=30),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='primary_color',
            field=models.CharField(default='#d4af37', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='secondary_color',
            field=models.CharField(default='#4a152d', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='spin_button_color',
            field=models.CharField(default='#d4af37', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='spin_button_text',
            field=models.CharField(default='SPIN FOR JEWELS', max_length=50),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='text_color',
            field=models.CharField(default='#fdfbf7', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='theme',
            field=models.CharField(choices=[('royal_jewellery', 'Royal Jewellery (Gold & Diamond Luxury)'), ('minimal_luxury', 'Minimal Luxury (Editorial & Restrained)'), ('luxury_black', 'Luxury Black (Dark Chrome & Champagne)'), ('pearl', 'Pearl Luxury (Cosmetics & Soft Gold)'), ('restaurant', 'Restaurant (Gourmet Amber & Warm Dining)'), ('coffee', 'Coffee Shop (Artisan Roast & Caramel)'), ('fashion', 'Fashion Editorial (Haute Couture)'), ('beauty', 'Beauty & Cosmetics (Rose & Glossy Glow)'), ('sports', 'Sports & Fitness (High Energy Athletic)'), ('electronics', 'Electronics & Cyber Technology'), ('automotive', 'Automotive (Metallic Chrome & Speed)'), ('real_estate', 'Real Estate & Architectural Luxury'), ('diwali', 'Diwali (Royal Lights & Diyas)'), ('navratri', 'Navratri (Garba Nights & Dandiya)'), ('holi', 'Holi (Color Blast & Powder Splash)'), ('christmas', 'Christmas (Winter Wonderland & Gifts)'), ('new_year', 'New Year (Midnight Fireworks Celebration)'), ('eid', 'Eid / Ramadan (Moonlight & Lanterns)'), ('eid_ul_fitr', 'Eid-ul-Fitr (Celebration & Emerald Glow)'), ('onam', 'Onam (Festival of Harvest & Pookalam)'), ('makar_sankranti', 'Makar Sankranti / Uttarayan (Kites & Sky)'), ('durga_puja', 'Durga Puja (Festive Red & Gold Traditions)'), ('valentines', 'Valentine’s (Romance & Rose Petals)'), ('womens_day', 'Women’s Day (Feminine Elegance & Lilac)'), ('halloween', 'Halloween (Dark Fantasy & Pumpkins)'), ('earth_eco', 'Earth & Eco (Sustainable Organic Green)'), ('summer_sale', 'Summer Sale (Sunlight & Tropical Breeze)'), ('winter_sale', 'Winter Sale (Frozen Ice & Snowflake Frost)'), ('monsoon_sale', 'Monsoon Sale (Rain Droplets & Ripples)'), ('flash_sale', 'Flash Sale (High Voltage Lightning & Speed)'), ('mega_sale', 'Mega Sale (Commercial % Discount Burst)'), ('clearance', 'Clearance Sale (Bold Retail Liquidation)'), ('grand_opening', 'Grand Opening (Celebration & Confetti)'), ('weekend_flash', 'Weekend Flash (Countdown Timer & Energy)')], default='royal_jewellery', max_length=50),
        ),
    ]
