# Generated by Django 5.2.9 on 2026-08-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_shopbranding_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbranding',
            name='intensity',
            field=models.CharField(blank=True, choices=[('subtle', 'Subtle (Low Animation)'), ('balanced', 'Balanced (Standard Premium Effects)'), ('dynamic', 'Dynamic (Maximum Promotional Effects)')], default='balanced', max_length=20, null=True),
        ),
    ]
