# Generated by Django 5.2.9 on 2026-08-30 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_shopbranding_intensity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('event_type', models.CharField(choices=[('festival', 'Festival'), ('special_day', 'Special Occasion / Day'), ('seasonal', 'Seasonal Event'), ('weekday', 'Weekday Theme')], default='festival', max_length=30)),
                ('country', models.CharField(blank=True, default='IN', max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('theme', models.CharField(choices=[('royal', 'Royal Gold'), ('luxury_black', 'Luxury Black'), ('pearl', 'Pearl Luxury'), ('aurora', 'Aurora'), ('glass', 'Glassmorphism'), ('neon', 'Cyber Neon'), ('emerald', 'Emerald'), ('burgundy', 'Burgundy Fashion'), ('modern_blue', 'Modern Blue'), ('festival', 'Festival Celebration'), ('diwali', 'Diwali Lights'), ('navratri', 'Navratri Garba'), ('holi', 'Holi Color Splash'), ('christmas', 'Christmas Holiday'), ('new_year', 'New Year Sparkle'), ('eid', 'Eid Celebration'), ('valentines', 'Valentine Romance'), ('summer_sale', 'Summer Tropical Sale'), ('winter_sale', 'Winter Frost Sale'), ('monsoon_sale', 'Monsoon Splash Sale'), ('flash_sale', 'Flash Sale Lightning'), ('clearance', 'Clearance Sale'), ('restaurant', 'Restaurant Dining'), ('coffee', 'Coffee Café'), ('playful', 'Playful Kids'), ('candy', 'Candy Sweet'), ('sports', 'Sports Energy'), ('minimal', 'Minimal Clean'), ('sunset', 'Sunset Warmth'), ('ocean', 'Ocean Wave'), ('floral', 'Floral Blossom'), ('premium_white', 'Premium White'), ('custom', 'Custom Theme')], default='festival', max_length=50)),
                ('priority', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🎉', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='system', max_length=50)),
                ('source_event_id', models.CharField(blank=True, max_length=100)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', 'start_date'],
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='auto_category_theme_adaptation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='auto_theme_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(default='IN', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='manual_theme_override',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='normal_theme',
            field=models.CharField(default='royal', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='override_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='region',
            field=models.CharField(default='Gujarat', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
        migrations.CreateModel(
            name='ThemeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_theme', models.CharField(max_length=50)),
                ('new_theme', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.calendarevent')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_audit_logs', to='core.shop')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
