# Generated by Django 5.2.9 on 2026-08-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_shop_pre_festival_days_alter_calendarevent_theme_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='couponredemption',
            options={'ordering': ['-redeemed_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='qrscanlog',
            options={'ordering': ['-scanned_at']},
        ),
        migrations.AlterModelOptions(
            name='spinresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='theme',
            field=models.CharField(choices=[('royal', 'Royal Gold'), ('royal_jewellery', 'Royal Jewellery (Gold & Ruby)'), ('luxury_black', 'Luxury Black'), ('minimal_luxury', 'Minimal Luxury'), ('pearl', 'Pearl Luxury (Beauty & Salon)'), ('aurora', 'Aurora Luminous'), ('glass', 'Glassmorphism Frosted'), ('neon', 'Cyber Neon (Gaming)'), ('emerald', 'Emerald Green'), ('burgundy', 'Burgundy Fashion'), ('fashion', 'Haute Couture Fashion'), ('modern_blue', 'Modern Blue Tech'), ('festival', 'Festival Celebration'), ('diwali', 'Diwali Lights & Dhanteras'), ('navratri', 'Navratri Garba'), ('holi', 'Holi Color Splash'), ('christmas', 'Christmas Holiday'), ('new_year', 'New Year Sparkle'), ('eid', 'Eid Celebration'), ('valentines', 'Valentine Romance'), ('halloween', 'Spooky Halloween'), ('uttarayan', 'Uttarayan Kite Festival'), ('summer_sale', 'Summer Tropical Sale'), ('winter_sale', 'Winter Frost Sale'), ('monsoon_sale', 'Monsoon Splash Sale'), ('flash_sale', 'Flash Sale Lightning'), ('clearance', 'Clearance Sale'), ('restaurant', 'Restaurant & Gourmet Dining'), ('coffee', 'Coffee Café & Bakery'), ('beauty', 'Cosmetics & Beauty Glow'), ('sports', 'Sports & Gym Energy'), ('automotive', 'Automotive Speed & Carbon'), ('playful', 'Playful Kids'), ('kids', 'Kids & Toys Playful'), ('candy', 'Candy Sweet'), ('minimal', 'Minimal Clean'), ('sunset', 'Sunset Warmth'), ('ocean', 'Ocean Wave'), ('floral', 'Floral Blossom'), ('premium_white', 'Premium White'), ('janmashtami', 'Krishna Janmashtami'), ('janmashtami_jewellery', 'Janmashtami Royal Jewellery'), ('janmashtami_sweets', 'Janmashtami Sweets & Butter Pot'), ('janmashtami_clothing', 'Janmashtami Festive Apparel'), ('janmashtami_kids', 'Janmashtami Bal Gopal Kids'), ('custom', 'Custom Theme')], default='festival', max_length=50),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='theme',
            field=models.CharField(choices=[('royal', 'Royal Gold'), ('royal_jewellery', 'Royal Jewellery (Gold & Ruby)'), ('luxury_black', 'Luxury Black'), ('minimal_luxury', 'Minimal Luxury'), ('pearl', 'Pearl Luxury (Beauty & Salon)'), ('aurora', 'Aurora Luminous'), ('glass', 'Glassmorphism Frosted'), ('neon', 'Cyber Neon (Gaming)'), ('emerald', 'Emerald Green'), ('burgundy', 'Burgundy Fashion'), ('fashion', 'Haute Couture Fashion'), ('modern_blue', 'Modern Blue Tech'), ('festival', 'Festival Celebration'), ('diwali', 'Diwali Lights & Dhanteras'), ('navratri', 'Navratri Garba'), ('holi', 'Holi Color Splash'), ('christmas', 'Christmas Holiday'), ('new_year', 'New Year Sparkle'), ('eid', 'Eid Celebration'), ('valentines', 'Valentine Romance'), ('halloween', 'Spooky Halloween'), ('uttarayan', 'Uttarayan Kite Festival'), ('summer_sale', 'Summer Tropical Sale'), ('winter_sale', 'Winter Frost Sale'), ('monsoon_sale', 'Monsoon Splash Sale'), ('flash_sale', 'Flash Sale Lightning'), ('clearance', 'Clearance Sale'), ('restaurant', 'Restaurant & Gourmet Dining'), ('coffee', 'Coffee Café & Bakery'), ('beauty', 'Cosmetics & Beauty Glow'), ('sports', 'Sports & Gym Energy'), ('automotive', 'Automotive Speed & Carbon'), ('playful', 'Playful Kids'), ('kids', 'Kids & Toys Playful'), ('candy', 'Candy Sweet'), ('minimal', 'Minimal Clean'), ('sunset', 'Sunset Warmth'), ('ocean', 'Ocean Wave'), ('floral', 'Floral Blossom'), ('premium_white', 'Premium White'), ('janmashtami', 'Krishna Janmashtami'), ('janmashtami_jewellery', 'Janmashtami Royal Jewellery'), ('janmashtami_sweets', 'Janmashtami Sweets & Butter Pot'), ('janmashtami_clothing', 'Janmashtami Festive Apparel'), ('janmashtami_kids', 'Janmashtami Bal Gopal Kids'), ('custom', 'Custom Theme')], default='royal', max_length=50),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['shop', 'timestamp'], name='core_activi_shop_id_d2e723_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='core_calend_is_acti_7cbb57_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['shop', 'status'], name='core_coupon_shop_id_7c0f82_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['shop', 'created_at'], name='core_coupon_shop_id_d9e69a_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['campaign', 'status'], name='core_coupon_campaig_4f45fc_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['redeemed_at'], name='core_coupon_redeeme_97a3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['shop', 'is_read', 'created_at'], name='core_notifi_shop_id_8d16cb_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanlog',
            index=models.Index(fields=['shop', 'scanned_at'], name='core_qrscan_shop_id_0fe396_idx'),
        ),
        migrations.AddIndex(
            model_name='spinresult',
            index=models.Index(fields=['shop', 'created_at'], name='core_spinre_shop_id_fcb88c_idx'),
        ),
        migrations.AddIndex(
            model_name='spinresult',
            index=models.Index(fields=['shop', 'campaign', 'created_at'], name='core_spinre_shop_id_3e746c_idx'),
        ),
        migrations.AddIndex(
            model_name='spinresult',
            index=models.Index(fields=['session_key', 'created_at'], name='core_spinre_session_0fa389_idx'),
        ),
    ]
