# Generated by Django 5.2.9 on 2026-08-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_activitylog_options_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_period_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_rupees',
            field=models.DecimalField(decimal_places=2, default=499.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(default='starter', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_display',
            field=models.CharField(default='₹499 / month', max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
