# Generated by Django 5.2.9 on 2026-08-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_plan_billing_period_days_plan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom Days')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.IntegerField(default=0),
        ),
    ]
