# Generated by Django 5.2.9 on 2026-09-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_planrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planrequest',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='planrequest',
            index=models.Index(fields=['status', 'created_at'], name='core_planre_status_f2cfb9_idx'),
        ),
    ]
