# Generated by Django 5.2.9 on 2026-09-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_planrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequest',
            name='request_type',
            field=models.CharField(choices=[('renewal', 'Renewal'), ('upgrade', 'Upgrade / Switch')], default='upgrade', max_length=20),
        ),
    ]
