# Generated by Django 5.2.9 on 2026-09-03 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='future_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='future_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscription',
            name='future_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_subscriptions', to='core.plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='future_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
