# Generated by Django 5.2.9 on 2026-09-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='theme',
            field=models.CharField(choices=[('royal', 'Royal Gold'), ('royal_jewellery', 'Royal Jewellery (Gold & Ruby)'), ('luxury_black', 'Luxury Black'), ('minimal_luxury', 'Minimal Luxury'), ('pearl', 'Pearl Luxury (Beauty & Salon)'), ('aurora', 'Aurora Luminous'), ('glass', 'Glassmorphism Frosted'), ('neon', 'Cyber Neon (Gaming)'), ('emerald', 'Emerald Green'), ('burgundy', 'Burgundy Fashion'), ('fashion', 'Haute Couture Fashion'), ('kurti', 'Kurti & Indian Ethnic Boutique'), ('modern_blue', 'Modern Blue Tech'), ('festival', 'Festival Celebration'), ('diwali', 'Diwali Lights & Dhanteras'), ('navratri', 'Navratri Garba'), ('holi', 'Holi Color Splash'), ('christmas', 'Christmas Holiday'), ('new_year', 'New Year Sparkle'), ('eid', 'Eid Celebration'), ('valentines', 'Valentine Romance'), ('halloween', 'Spooky Halloween'), ('uttarayan', 'Uttarayan Kite Festival'), ('summer_sale', 'Summer Tropical Sale'), ('winter_sale', 'Winter Frost Sale'), ('monsoon_sale', 'Monsoon Splash Sale'), ('flash_sale', 'Flash Sale Lightning'), ('clearance', 'Clearance Sale'), ('restaurant', 'Restaurant & Gourmet Dining'), ('coffee', 'Coffee Café & Bakery'), ('beauty', 'Cosmetics & Beauty Glow'), ('sports', 'Sports & Gym Energy'), ('automotive', 'Automotive Speed & Carbon'), ('playful', 'Playful Kids'), ('kids', 'Kids & Toys Playful'), ('candy', 'Candy Sweet'), ('minimal', 'Minimal Clean'), ('sunset', 'Sunset Warmth'), ('ocean', 'Ocean Wave'), ('floral', 'Floral Blossom'), ('premium_white', 'Premium White'), ('janmashtami', 'Krishna Janmashtami'), ('janmashtami_jewellery', 'Janmashtami Royal Jewellery'), ('janmashtami_sweets', 'Janmashtami Sweets & Butter Pot'), ('janmashtami_clothing', 'Janmashtami Festive Apparel'), ('janmashtami_kids', 'Janmashtami Bal Gopal Kids'), ('custom', 'Custom Theme')], default='festival', max_length=50),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='theme',
            field=models.CharField(choices=[('royal', 'Royal Gold'), ('royal_jewellery', 'Royal Jewellery (Gold & Ruby)'), ('luxury_black', 'Luxury Black'), ('minimal_luxury', 'Minimal Luxury'), ('pearl', 'Pearl Luxury (Beauty & Salon)'), ('aurora', 'Aurora Luminous'), ('glass', 'Glassmorphism Frosted'), ('neon', 'Cyber Neon (Gaming)'), ('emerald', 'Emerald Green'), ('burgundy', 'Burgundy Fashion'), ('fashion', 'Haute Couture Fashion'), ('kurti', 'Kurti & Indian Ethnic Boutique'), ('modern_blue', 'Modern Blue Tech'), ('festival', 'Festival Celebration'), ('diwali', 'Diwali Lights & Dhanteras'), ('navratri', 'Navratri Garba'), ('holi', 'Holi Color Splash'), ('christmas', 'Christmas Holiday'), ('new_year', 'New Year Sparkle'), ('eid', 'Eid Celebration'), ('valentines', 'Valentine Romance'), ('halloween', 'Spooky Halloween'), ('uttarayan', 'Uttarayan Kite Festival'), ('summer_sale', 'Summer Tropical Sale'), ('winter_sale', 'Winter Frost Sale'), ('monsoon_sale', 'Monsoon Splash Sale'), ('flash_sale', 'Flash Sale Lightning'), ('clearance', 'Clearance Sale'), ('restaurant', 'Restaurant & Gourmet Dining'), ('coffee', 'Coffee Café & Bakery'), ('beauty', 'Cosmetics & Beauty Glow'), ('sports', 'Sports & Gym Energy'), ('automotive', 'Automotive Speed & Carbon'), ('playful', 'Playful Kids'), ('kids', 'Kids & Toys Playful'), ('candy', 'Candy Sweet'), ('minimal', 'Minimal Clean'), ('sunset', 'Sunset Warmth'), ('ocean', 'Ocean Wave'), ('floral', 'Floral Blossom'), ('premium_white', 'Premium White'), ('janmashtami', 'Krishna Janmashtami'), ('janmashtami_jewellery', 'Janmashtami Royal Jewellery'), ('janmashtami_sweets', 'Janmashtami Sweets & Butter Pot'), ('janmashtami_clothing', 'Janmashtami Festive Apparel'), ('janmashtami_kids', 'Janmashtami Bal Gopal Kids'), ('custom', 'Custom Theme')], default='royal', max_length=50),
        ),
    ]
