# Generated by Django 5.2.16 on 2026-09-30 12:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_repair_decimal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='design_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_rupees',
            field=models.DecimalField(decimal_places=2, default=Decimal('499.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))]),
        ),
        migrations.AlterField(
            model_name='prize',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='prize',
            name='fixed_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))]),
        ),
    ]
