# Generated by Django 5.2.16 on 2026-09-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_prize_design_config_alter_plan_price_rupees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='design_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
