# Generated by Django 5.2.9 on 2026-10-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_prize_design_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='center_logo',
            field=models.ImageField(blank=True, null=True, upload_to='wheel_center_logos/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='wheel_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
